apiVersion: v1alpha1
kind: Setting
metadata:
  name: halo-theme-lapis-setting
spec:
  forms:
    - group: global
      label: 全局
      formSchema:
        - $formkit: checkbox
          name: enable_resize_image
          label: 自动调整图片大小
          value: false
          help: 开启后，文章内的图片会根据不同设备的屏幕大小自动调整宽高并居中。
        - $formkit: text
          name: beian
          label: 备案号
          value: ""
          help: 备案号会显示在所有页面最下方
        - $formkit: text
          name: gongan_text
          label: 公安备案号
          value: ""
          help: 公安备案号文字部分
        - $formkit: text
          name: gongan_link
          label: 公安备案链接
          value: "https://beian.mps.gov.cn/#/query/webSearch?code="
          help: 公安备案号的链接，在code后面添加公安备案号的数字部分即可跳转到对应的公安备案信息页面

    - group: links
      label: 链接
      formSchema:
        - $formkit: checkbox
          name: round_avatar
          label: 圆形 Logo
          value: true
          help: 开启后，网站 Logo 会显示为圆形，否则为方形。
