apiVersion: v1alpha1
kind: Setting
metadata:
  name: halo-theme-lapis-setting
spec:
  forms:
    - group: global
      label: 全局
      formSchema:
        - $formkit: text
          name: beian
          label: 备案号
          value: ""
          help: 备案号会显示在所有页面最下方
